package stores.articles.v;

import core.c.ErrorHandler;
import core.c.Feedbackable;
import core.c.Reloadable;
import core.m.DatabaseException;
import core.v.ApplicationDialog;
import java.sql.SQLException;
import stores.articles.c.TiresService;
import stores.articles.m.TireSize;

/**
 *
 * @author MRKACZOR
 */
public class AddEditTireSizeDialog extends ApplicationDialog
{
  private TireSize _tireSize;
  private Feedbackable _parent;
  private final boolean _editMode;

  public AddEditTireSizeDialog(boolean modal, Reloadable parent)
  {
    super(modal, parent);
    if(parent instanceof Feedbackable)
      _parent = (Feedbackable)parent;
    _editMode = false;
    _tireSize = new TireSize();
    initComponents();
  }

  public AddEditTireSizeDialog(boolean modal, Reloadable parent, TireSize tireSize)
  {
    super(modal, parent);
    if(parent instanceof Feedbackable)
      _parent = (Feedbackable)parent;
    _editMode = true;
    _tireSize = tireSize.clone();
    initComponents();
	initTextFields();
  }
  
  private void initTextFields() {
	  initWidthTextField();
	  initProfileTextField();
	  initDiametertextField();
  }
  
  private void initWidthTextField() {
	  _widthTextField.setText(_tireSize.getWidth());
  }
  
  private void initProfileTextField() {
	  _profileTextField.setText(_tireSize.getProfile());
  }
  
  private void initDiametertextField() {
	  _diameterTextField.setText(_tireSize.getDiameter());
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        _widthLabel = new javax.swing.JLabel();
        _widthTextField = new javax.swing.JTextField();
        _profileLabel = new javax.swing.JLabel();
        _profileTextField = new javax.swing.JTextField();
        _diameterLabel = new javax.swing.JLabel();
        _diameterTextField = new javax.swing.JTextField();
        bSubmit = new javax.swing.JButton();
        bCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(250, 180));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText(_editMode?"Edycja rozmiaru opony":"Nowy rozmiar opony");
        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        _widthLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        _widthLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        _widthLabel.setText("Szerokość:");

        _widthTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        _widthTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                _widthTextFieldFocusLost(evt);
            }
        });

        _profileLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        _profileLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        _profileLabel.setText("Profil:");

        _profileTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        _profileTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                _profileTextFieldFocusLost(evt);
            }
        });

        _diameterLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        _diameterLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        _diameterLabel.setText("Średnica:");

        _diameterTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        _diameterTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                _diameterTextFieldFocusLost(evt);
            }
        });

        bSubmit.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        bSubmit.setText("Zapisz");
        bSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSubmitActionPerformed(evt);
            }
        });

        bCancel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        bCancel.setText("Anuluj");
        bCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSeparator1)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(_profileLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(_profileTextField))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(_widthLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(_widthTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(_diameterLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(_diameterTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 52, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(bSubmit)
                        .addGap(20, 20, 20)
                        .addComponent(bCancel)))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {_diameterLabel, _diameterTextField, _profileLabel, _profileTextField, _widthLabel, _widthTextField});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(_widthLabel)
                    .addComponent(_widthTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(_profileLabel)
                    .addComponent(_profileTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(_diameterLabel)
                    .addComponent(_diameterTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bSubmit)
                    .addComponent(bCancel))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {_diameterLabel, _diameterTextField, _profileLabel, _profileTextField, _widthLabel, _widthTextField});

        pack();
    }// </editor-fold>//GEN-END:initComponents

  private void bSubmitActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_bSubmitActionPerformed
  {//GEN-HEADEREND:event_bSubmitActionPerformed
    try
    {
      if(_editMode)
        TiresService.getInstance().updateTireSize(_tireSize);
      else
        _tireSize = TiresService.getInstance().addTireSize(_tireSize);
      if(_parent!=null)
        _parent.sendFeedback(_tireSize);
      close(true);
    }
    catch(DatabaseException|SQLException ex)
    {
      ErrorHandler.getInstance().reportError(ex);
    }
  }//GEN-LAST:event_bSubmitActionPerformed

  private void bCancelActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_bCancelActionPerformed
  {//GEN-HEADEREND:event_bCancelActionPerformed
    close();
  }//GEN-LAST:event_bCancelActionPerformed

  private void _widthTextFieldFocusLost(java.awt.event.FocusEvent evt)//GEN-FIRST:event__widthTextFieldFocusLost
  {//GEN-HEADEREND:event__widthTextFieldFocusLost
    _tireSize.setWidth(_widthTextField.getText());
  }//GEN-LAST:event__widthTextFieldFocusLost

  private void _profileTextFieldFocusLost(java.awt.event.FocusEvent evt)//GEN-FIRST:event__profileTextFieldFocusLost
  {//GEN-HEADEREND:event__profileTextFieldFocusLost
    _tireSize.setProfile(_profileTextField.getText());
  }//GEN-LAST:event__profileTextFieldFocusLost

  private void _diameterTextFieldFocusLost(java.awt.event.FocusEvent evt)//GEN-FIRST:event__diameterTextFieldFocusLost
  {//GEN-HEADEREND:event__diameterTextFieldFocusLost
    _tireSize.setDiameter(_diameterTextField.getText());
  }//GEN-LAST:event__diameterTextFieldFocusLost

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel _diameterLabel;
    private javax.swing.JTextField _diameterTextField;
    private javax.swing.JLabel _profileLabel;
    private javax.swing.JTextField _profileTextField;
    private javax.swing.JLabel _widthLabel;
    private javax.swing.JTextField _widthTextField;
    private javax.swing.JButton bCancel;
    private javax.swing.JButton bSubmit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
