/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package stores.articles.v;

import core.c.ErrorHandler;
import core.c.Reloadable;
import core.c.ViewManager;
import core.v.ApplicationDialog;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import stores.articles.c.TiresService;
import stores.articles.m.TireSize;
import stores.articles.m.Tread;

/**
 *
 * @author tobikster
 */
public class TreadsListDialog extends ApplicationDialog implements Reloadable {
	public static final String[] TREADS_TABLE_HEADERS = {
		"Nazwa"
	};
	/**
	 * Creates new form TreadsListDialog
	 */
	public TreadsListDialog(boolean modal, Reloadable parent) throws SQLException {
		super(modal, parent);
		initComponents();
		initTreadsTableModel();
	}
	
	/**
	 *
	 */
	@Override
	public void reload() {
		try {
			initTreadsTableModel();
		}
		catch (SQLException ex) {
			ErrorHandler.getInstance().reportError(ex);
		}
	}
	
	private void initTreadsTableModel() throws SQLException {
		_treadsTable.setModel(getTreadsTableModel());
	}
	
	private TableModel getTreadsTableModel() throws SQLException {
		List<Tread> treads = TiresService.getInstance().getTreads();
		Object[][] tableData = new Object[treads.size()][];
		for(int i = 0; i < tableData.length; ++i) {
			tableData[i] = new Tread[1];
			tableData[i][0] = treads.get(i);
		}
		return new DefaultTableModel(tableData, TREADS_TABLE_HEADERS);
	}

	/**
	 * This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        _titleLabel = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        _treadsTableScrollPane = new javax.swing.JScrollPane();
        _treadsTable = new javax.swing.JTable();
        _actionsPanel = new javax.swing.JPanel();
        _addButton = new javax.swing.JButton();
        _removeButton = new javax.swing.JButton();
        _editButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        _titleLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        _titleLabel.setText("Bieżniki opon");

        _treadsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        _treadsTableScrollPane.setViewportView(_treadsTable);

        _addButton.setText("Dodaj");
        _addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _addButtonActionPerformed(evt);
            }
        });

        _removeButton.setText("Usuń");

        _editButton.setText("Edycja");

        javax.swing.GroupLayout _actionsPanelLayout = new javax.swing.GroupLayout(_actionsPanel);
        _actionsPanel.setLayout(_actionsPanelLayout);
        _actionsPanelLayout.setHorizontalGroup(
            _actionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, _actionsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(_removeButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(_editButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(_addButton)
                .addContainerGap())
        );
        _actionsPanelLayout.setVerticalGroup(
            _actionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, _actionsPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(_actionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(_addButton)
                    .addComponent(_removeButton)
                    .addComponent(_editButton))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(_titleLabel)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(_actionsPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(_treadsTableScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(_titleLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(_treadsTableScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(_actionsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void _addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__addButtonActionPerformed
//        ViewManager.getInstance().showDialog(new AddEditTreadDialog(true, this, null));
    }//GEN-LAST:event__addButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel _actionsPanel;
    private javax.swing.JButton _addButton;
    private javax.swing.JButton _editButton;
    private javax.swing.JButton _removeButton;
    private javax.swing.JLabel _titleLabel;
    private javax.swing.JTable _treadsTable;
    private javax.swing.JScrollPane _treadsTableScrollPane;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
