package core.v;

import core.c.AuthenticationService;
import core.c.ErrorHandler;
import core.c.ViewManager;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JPanel;
import stores.articles.v.TireSizesListDialog;
import stores.articles.v.TreadsListDialog;
import stores.producers.v.ProducersListDialog;

/**
 *
 * @author tobikster
 */
public class MainWindow extends javax.swing.JFrame
{
  /**
   * Creates new form MainWindow
   */
  public MainWindow()
  {
    initComponents();
  }
  
  public JPanel getMainPanel() {
    return jpMainPanel;
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpMainPanel = new javax.swing.JPanel();
        jpMainMenu = new core.v.MainMenuView();
        jMenuBar1 = new javax.swing.JMenuBar();
        mFile = new javax.swing.JMenu();
        miLogout = new javax.swing.JMenuItem();
        mFile_Exit = new javax.swing.JMenuItem();
        mEdit = new javax.swing.JMenu();
        mKnowlageBase = new javax.swing.JMenu();
        miProducers = new javax.swing.JMenuItem();
        miTreads = new javax.swing.JMenuItem();
        miTireSizes = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Mechaniker v1.0");
        setMinimumSize(new java.awt.Dimension(800, 600));
        setPreferredSize(new java.awt.Dimension(800, 600));
        getContentPane().setLayout(new java.awt.CardLayout());

        jpMainPanel.setLayout(new java.awt.BorderLayout());
        jpMainPanel.add(jpMainMenu, java.awt.BorderLayout.CENTER);

        getContentPane().add(jpMainPanel, "card2");

        mFile.setText("Plik");

        miLogout.setText("Wyloguj");
        miLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miLogoutActionPerformed(evt);
            }
        });
        mFile.add(miLogout);

        mFile_Exit.setText("Zakończ");
        mFile_Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mFile_ExitActionPerformed(evt);
            }
        });
        mFile.add(mFile_Exit);

        jMenuBar1.add(mFile);

        mEdit.setText("Edycja");
        jMenuBar1.add(mEdit);

        mKnowlageBase.setText("Baza wiedzy");

        miProducers.setText("Producenci");
        miProducers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miProducersActionPerformed(evt);
            }
        });
        mKnowlageBase.add(miProducers);

        miTreads.setText("Bieżniki opon");
        miTreads.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miTreadsActionPerformed(evt);
            }
        });
        mKnowlageBase.add(miTreads);

        miTireSizes.setText("Rozmiary opon");
        miTireSizes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miTireSizesActionPerformed(evt);
            }
        });
        mKnowlageBase.add(miTireSizes);

        jMenuBar1.add(mKnowlageBase);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

  private void mFile_ExitActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_mFile_ExitActionPerformed
  {//GEN-HEADEREND:event_mFile_ExitActionPerformed
    System.exit(0);
  }//GEN-LAST:event_mFile_ExitActionPerformed

  private void miLogoutActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_miLogoutActionPerformed
  {//GEN-HEADEREND:event_miLogoutActionPerformed
    AuthenticationService.getInstance().logout();
  }//GEN-LAST:event_miLogoutActionPerformed

    private void miProducersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miProducersActionPerformed
		try {
			ViewManager.getInstance().showDialog(new ProducersListDialog(true, null));
		}
		catch (SQLException ex) {
			ErrorHandler.getInstance().reportError(ex);
		}
    }//GEN-LAST:event_miProducersActionPerformed

    private void miTreadsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miTreadsActionPerformed
		try {
			ViewManager.getInstance().showDialog(new TreadsListDialog(false, null));
		}
		catch (SQLException ex) {
			ErrorHandler.getInstance().reportError(ex);
		}
    }//GEN-LAST:event_miTreadsActionPerformed

    private void miTireSizesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miTireSizesActionPerformed
		try {
			ViewManager.getInstance().showDialog(new TireSizesListDialog(false, null));
		}
		catch (SQLException ex) {
			ErrorHandler.getInstance().reportError(ex);
		}
    }//GEN-LAST:event_miTireSizesActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private core.v.MainMenuView jpMainMenu;
    private javax.swing.JPanel jpMainPanel;
    private javax.swing.JMenu mEdit;
    private javax.swing.JMenu mFile;
    private javax.swing.JMenuItem mFile_Exit;
    private javax.swing.JMenu mKnowlageBase;
    private javax.swing.JMenuItem miLogout;
    private javax.swing.JMenuItem miProducers;
    private javax.swing.JMenuItem miTireSizes;
    private javax.swing.JMenuItem miTreads;
    // End of variables declaration//GEN-END:variables
}
