/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package articles.v;

import javax.swing.table.DefaultTableModel;

/**
 *
 * @author tobikster
 */
public class ArticlesListView extends javax.swing.JPanel {
	private static final String[] _ARTICLES_LIST_COLUMN_NAMES = new String[] {
		"Nazwa",
		"Numer katalogowy",
		"Grupa towarowa",
		"Producent",
		"Liczba",
		"Cena",
		"Marża"
	};

	/**
	 * Creates new form ArticlesListView
	 */
	public ArticlesListView() {
		initComponents();
	}
	
	public void setArticlesListValues(Object[][] values) {
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        _navPanel = new javax.swing.JPanel();
        _backButton = new javax.swing.JButton();

        jTable1.setModel(new DefaultTableModel(_ARTICLES_LIST_COLUMN_NAMES, 0));
        jScrollPane2.setViewportView(jTable1);
        jTable1.getColumnModel().getColumn(0).setHeaderValue("Nazwa");
        jTable1.getColumnModel().getColumn(1).setHeaderValue("Numer katalogowy");
        jTable1.getColumnModel().getColumn(2).setHeaderValue("Grupa towarowa");
        jTable1.getColumnModel().getColumn(3).setHeaderValue("Producent");
        jTable1.getColumnModel().getColumn(4).setHeaderValue("Liczba");
        jTable1.getColumnModel().getColumn(5).setHeaderValue("Cena");
        jTable1.getColumnModel().getColumn(6).setHeaderValue("Marża");

        _backButton.setText("Powrót");

        javax.swing.GroupLayout _navPanelLayout = new javax.swing.GroupLayout(_navPanel);
        _navPanel.setLayout(_navPanelLayout);
        _navPanelLayout.setHorizontalGroup(
            _navPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(_navPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(_backButton)
                .addContainerGap(221, Short.MAX_VALUE))
        );
        _navPanelLayout.setVerticalGroup(
            _navPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, _navPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(_backButton)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(_navPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(_navPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton _backButton;
    private javax.swing.JPanel _navPanel;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
