package stores.producers.v;

import core.c.ErrorHandler;
import core.c.Reloadable;
import core.c.ViewManager;
import core.v.ApplicationDialog;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import stores.producers.c.ProducersService;
import stores.producers.m.Producer;

/**
 *
 * @author tobikster
 */
public class ProducersListDialog extends ApplicationDialog implements Reloadable {
	public static final String[] PRODUCERS_TABLE_HEADERS = {
		"Nazwa"
	};

	/**
	 * Creates new form ProducersListDialog
	 */
	public ProducersListDialog(boolean modal, Reloadable reloadableParent) throws SQLException {
		super(modal, reloadableParent);
		initComponents();
		initTables();
	}

	@Override
	public void reload() {
		try {
			initTables();
		}
		catch (SQLException ex) {
			ErrorHandler.getInstance().reportError(ex);
		}
	}

	private void initTables() throws SQLException {
		initProducersTable();
	}

	private void initProducersTable() throws SQLException {
		_producersTable.setModel(getProducersTableModel());
	}

	private TableModel getProducersTableModel() throws SQLException {
		List<Producer> producers = ProducersService.getInstance().getProducers();
		Object[][] tableData = new Producer[producers.size()][];
		for (int i = 0; i < tableData.length; ++i) {
			tableData[i] = new Producer[1];
			tableData[i][0] = producers.get(i);
		}
		return new DefaultTableModel(tableData, PRODUCERS_TABLE_HEADERS);
	}

	/**
	 * This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        _titleLabel = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        _producersTableScrollPane = new javax.swing.JScrollPane();
        _producersTable = new javax.swing.JTable();
        _actionsPanel = new javax.swing.JPanel();
        _removeButton = new javax.swing.JButton();
        _addButton = new javax.swing.JButton();
        _editButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        _titleLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        _titleLabel.setText("Producenci");

        _producersTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        _producersTableScrollPane.setViewportView(_producersTable);

        _actionsPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        _removeButton.setText("Usuń");
        _removeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _removeButtonActionPerformed(evt);
            }
        });

        _addButton.setText("Dodaj");
        _addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _addButtonActionPerformed(evt);
            }
        });

        _editButton.setText("Edytuj");
        _editButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _editButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout _actionsPanelLayout = new javax.swing.GroupLayout(_actionsPanel);
        _actionsPanel.setLayout(_actionsPanelLayout);
        _actionsPanelLayout.setHorizontalGroup(
            _actionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(_actionsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(_removeButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addComponent(_editButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addComponent(_addButton)
                .addContainerGap())
        );
        _actionsPanelLayout.setVerticalGroup(
            _actionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, _actionsPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(_actionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(_removeButton)
                    .addComponent(_addButton)
                    .addComponent(_editButton))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(_titleLabel)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(_producersTableScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(_actionsPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(_titleLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(_producersTableScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(_actionsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void _addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__addButtonActionPerformed
		ViewManager.getInstance().showDialog(new AddEditProducerDialog(true, this));
    }//GEN-LAST:event__addButtonActionPerformed

    private void _editButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__editButtonActionPerformed
		if (_producersTable.getSelectedRow() >= 0) {
			ViewManager.getInstance().showDialog(new AddEditProducerDialog(true, this, ((Producer) (_producersTable.getValueAt(_producersTable.getSelectedRow(), 0))).clone()));
		}
    }//GEN-LAST:event__editButtonActionPerformed

    private void _removeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__removeButtonActionPerformed
		if (_producersTable.getSelectedRow() >= 0) {
			try {
				Producer producer = (Producer) (_producersTable.getValueAt(_producersTable.getSelectedRow(), 0));

				int removability = ProducersService.getInstance().checkProducerRemovability(producer);


				boolean removeProducer = false;

				switch (removability) {
					case 0:
						removeProducer = JOptionPane.showOptionDialog(this, "Czy na pewno chcesz usunąć producenta \"" + producer.getName() + "\"", "Usuwanie producenta", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE, null, new String[]{"Tak", "Nie"}, "Nie") == 0;
						break;

					case -1:
						removeProducer = JOptionPane.showOptionDialog(this, "Usunięcie producenta spowoduje usunięcie powiązanych z nim opon lub części. Czy chcesz kontynuować?", "Usuwanie producenta", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE, null, new String[]{"Tak", "Nie"}, "Nie") == 0;
						break;

					case -2:
						JOptionPane.showOptionDialog(this, "Usunięcie producenta nie jest możliwe, ponieważ spowodowałoby to usunięcie opon lub części z niezerowym stanem magazynowym!", "Usuwanie producenta", JOptionPane.OK_OPTION, JOptionPane.WARNING_MESSAGE, null, new String[]{"OK"}, "OK");
						removeProducer = false;
						break;
				}

				if (removeProducer) {
					if (ProducersService.getInstance().removeProducer(producer)) {
						reload();
						JOptionPane.showMessageDialog(this, "Producent " + producer.getName() + " usunięty pomyślnie!", "Usuwanie producenta", JOptionPane.INFORMATION_MESSAGE);
					}
					else {
						JOptionPane.showMessageDialog(this, "Producent " + producer.getName() + " nie został usunięty!", "Usuwanie producenta", JOptionPane.WARNING_MESSAGE);
					}
				}
			}
			catch (SQLException ex) {
				ErrorHandler.getInstance().reportError(ex);
			}
		}
    }//GEN-LAST:event__removeButtonActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel _actionsPanel;
    private javax.swing.JButton _addButton;
    private javax.swing.JButton _editButton;
    private javax.swing.JTable _producersTable;
    private javax.swing.JScrollPane _producersTableScrollPane;
    private javax.swing.JButton _removeButton;
    private javax.swing.JLabel _titleLabel;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}