/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package services.v;

import core.c.ErrorHandler;
import core.c.Reloadable;
import core.m.DatabaseException;
import core.v.ApplicationDialog;
import finance.c.FinanceService;
import finance.m.VATRate;
import java.sql.SQLException;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import services.c.ServicesGroupsService;
import services.m.ServicesGroup;

/**
 *
 * @author MRKACZOR
 */
public class AddEditServicesGroupDialog extends ApplicationDialog
{
  private final boolean _editMode;
  private ServicesGroup _group;

  /**
   * Creates new form AddEditServicesGroupDialog
   */
  public AddEditServicesGroupDialog(boolean modal, Reloadable parent)
  {
    super(modal, parent);
    _editMode = false;
    _group = new ServicesGroup();
    initComponents();
    initialize();
  }

  public AddEditServicesGroupDialog(boolean modal, Reloadable parent, ServicesGroup group)
  {
    super(modal, parent);
    _editMode = true;
    _group = group.clone();
    initComponents();
    initialize();
  }

  private void loadVATRateList() {
    DefaultComboBoxModel<VATRate> vatRates = new DefaultComboBoxModel<>();
    try {
      List<VATRate> rates = FinanceService.getInstance().getVatRates();
      for(VATRate rate : rates) {
        vatRates.addElement(rate);
      }
    } catch(SQLException ex) {
      ErrorHandler.getInstance().reportError(ex);
    }
    _VATRatesList.setModel(vatRates);
  }
  
  private void initialize() {
    loadVATRateList();
    if(_editMode) {
      _nameTextField.setText(_group.getName());
      _VATRatesList.setSelectedIndex(findIndexForItem(_group.getVat()));
    } else {
      _group.setName(_nameTextField.getText());
      _group.setVat((VATRate)_VATRatesList.getSelectedItem());
    }
  }

  private int findIndexForItem(VATRate vatRate) {
    for(int i=0;i<_VATRatesList.getItemCount();i++) {
      if(((VATRate)_VATRatesList.getItemAt(i)).getId().equals(vatRate.getId()))
        return i;
    }
    return 0;
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        _nameLabel = new javax.swing.JLabel();
        _VATRateLabel = new javax.swing.JLabel();
        _nameTextField = new javax.swing.JTextField();
        _VATRatesList = new javax.swing.JComboBox();
        _okButton = new javax.swing.JButton();
        _cancelButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(280, 160));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText(_editMode?"Edycja działu usług":"Nowy dział usług");
        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        _nameLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        _nameLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        _nameLabel.setText("Nazwa:");

        _VATRateLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        _VATRateLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        _VATRateLabel.setText("Stawka VAT:");

        _nameTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                _nameTextFieldFocusLost(evt);
            }
        });

        _VATRatesList.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        _VATRatesList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _VATRatesListActionPerformed(evt);
            }
        });

        _okButton.setText("Zapisz");
        _okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _okButtonActionPerformed(evt);
            }
        });

        _cancelButton.setText("Anuluj");
        _cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _cancelButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSeparator1)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(_VATRateLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(_VATRatesList, 0, 122, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(_nameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(_nameTextField)))
                        .addGap(32, 32, 32))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(_okButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(_cancelButton)))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {_cancelButton, _okButton});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(_nameLabel)
                    .addComponent(_nameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(_VATRateLabel)
                    .addComponent(_VATRatesList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(_cancelButton)
                    .addComponent(_okButton))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {_cancelButton, _okButton});

        pack();
    }// </editor-fold>//GEN-END:initComponents

  private void _okButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event__okButtonActionPerformed
  {//GEN-HEADEREND:event__okButtonActionPerformed
    try {
      if(_editMode) {
        ServicesGroupsService.getInstance().updateServicesGroup(_group);
      } else {
        ServicesGroupsService.getInstance().addServicesGroup(_group);
      }
      close(true);
    } catch(DatabaseException|SQLException ex) {
      ErrorHandler.getInstance().reportError(ex);
    }
  }//GEN-LAST:event__okButtonActionPerformed

  private void _cancelButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event__cancelButtonActionPerformed
  {//GEN-HEADEREND:event__cancelButtonActionPerformed
    close(false);
  }//GEN-LAST:event__cancelButtonActionPerformed

  private void _nameTextFieldFocusLost(java.awt.event.FocusEvent evt)//GEN-FIRST:event__nameTextFieldFocusLost
  {//GEN-HEADEREND:event__nameTextFieldFocusLost
    _group.setName(_nameTextField.getText());
  }//GEN-LAST:event__nameTextFieldFocusLost

  private void _VATRatesListActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event__VATRatesListActionPerformed
  {//GEN-HEADEREND:event__VATRatesListActionPerformed
    _group.setVat((VATRate)_VATRatesList.getSelectedItem());
  }//GEN-LAST:event__VATRatesListActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel _VATRateLabel;
    private javax.swing.JComboBox _VATRatesList;
    private javax.swing.JButton _cancelButton;
    private javax.swing.JLabel _nameLabel;
    private javax.swing.JTextField _nameTextField;
    private javax.swing.JButton _okButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
